version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Setting up environment..."
      - python -m venv eb_venv
      - . eb_venv/bin/activate
      - pip install --upgrade pip
      - 'pip install --only-binary=:all: --no-cache-dir -r requirements.txt'
      - deactivate
      - rm requirements.txt

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '.git/**/*'